language: ruby
rvm:
- 2.7.2
- jruby
env:
  global:
    secure: tqfjexTC8rIoBufMNBgxVGsE4aNCSSa+tgV2yxVnVAUbcL5u5m79VyNclZ4eC7oge4FR+6nO/ZBnoE4bVlOE6rYb5eP9702mHImsNKC4TA3mXPiljJiEaK71rXkT4BjIoK1KS9W5vP54dPXAH74FzREA88L8/FJFQsTagYMWFz5z94ti2wM2Y3yxegjne6bbGXufy8x9nfB+ekjlrQRowTj405teioj/0p7rw8ZguSs/7A6/p530LZS+ap5xcsBIlJRDXlba7FKsgpefmUvCYmQ5RxycdwhJ6pBS6Fy6FYXD7Rn/m6cqjtqMidF8OmsUNpc9Z1kt+NhQkahWyKVOo9G3J207qY+Y/9dZNwT8v2YERtX62fQkpLwhYquEvyNCqnE/2t8cKqQ1Rlag89YwnFnNqNzL5SiysKEoLepMRhFoUrLdnuDIHnaPU+6pYGNr9x1L980WTNDNXdoAAW4TrwmtxdNFRrJUMB3y9p3Er4j2ulyrp9mYg74P0SpomEVkcNP2EykY/MIM2jxNd8ZPp/nlWeL+iIJ1VGJRQfwCiIPw0m5svc45lL3AbqzeJCaSJqvDXoFz+zHtlzLNFIA7gMNtdixsQLDjx47ATOhxgeMrkzdQnGTJYWcBbKV+kwYStMABEbSuW9l6uJ5K3ALz1IeGmdKQlYe2lO1FpXmeT4A=
before_install:
    - gem install bundler
