language: ruby
rvm:
- 2.7.2
env:
  global:
    secure: tqfjexTC8rIoBufMNBgxVGsE4aNCSSa+tgV2yxVnVAUbcL5u5m79VyNclZ4eC7oge4FR+6nO/ZBnoE4bVlOE6rYb5eP9702mHImsNKC4TA3mXPiljJiEaK71rXkT4BjIoK1KS9W5vP54dPXAH74FzREA88L8/FJFQsTagYMWFz5z94ti2wM2Y3yxegjne6bbGXufy8x9nfB+ekjlrQRowTj405teioj/0p7rw8ZguSs/7A6/p530LZS+ap5xcsBIlJRDXlba7FKsgpefmUvCYmQ5RxycdwhJ6pBS6Fy6FYXD7Rn/m6cqjtqMidF8OmsUNpc9Z1kt+NhQkahWyKVOo9G3J207qY+Y/9dZNwT8v2YERtX62fQkpLwhYquEvyNCqnE/2t8cKqQ1Rlag89YwnFnNqNzL5SiysKEoLepMRhFoUrLdnuDIHnaPU+6pYGNr9x1L980WTNDNXdoAAW4TrwmtxdNFRrJUMB3y9p3Er4j2ulyrp9mYg74P0SpomEVkcNP2EykY/MIM2jxNd8ZPp/nlWeL+iIJ1VGJRQfwCiIPw0m5svc45lL3AbqzeJCaSJqvDXoFz+zHtlzLNFIA7gMNtdixsQLDjx47ATOhxgeMrkzdQnGTJYWcBbKV+kwYStMABEbSuW9l6uJ5K3ALz1IeGmdKQlYe2lO1FpXmeT4A=
before_install:
- gem install bundler
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  api_key:
    secure: QOlbw0olYp8yDpZdEfZyfF0AdjhqKrwzGXXoRayDh93CV5FmPyWth0HqvbN/69QYfhJPlFUvK4mGy9iE8t4aumE+gjLcbJcUo/7WITYZWLEbyuKGyslnH3w1hOUrfb05Uu2PsADBj2DUJrhDeErm3j+uSSJwRnRdqAkVhY1pYaHLeXT6LcW/QbZ823GRXy+wkpp5lu6QQfDIjdCoVAS92Jjjl/+5GKxv/BnDOD8mhLhoEdzR1GQTVY+eujcB/kG5PvvcHVJYKEPfEzyP9bjDo22+1qR1LfMaimAgTZpghqs1csRT5E7aOgUCLgxbF84Yt8yB4O00t82CoewfJIZkZS1hC9eRHPGuWEJ8xq2xfL1zZhFz3k8fbA5pFbsQrWmrslNFwMvUnz7xSFa6Vqps9V9dQiFCSHhxBa/0X0F6ZJQKjHAEgPkRsLJPM6FqVAeykcYaCS3miypdprXbO816zlwGineg0wD2WLFI4V8z+CJkUlP3/TRTfKLYAb3hOdVzSd9lOo2YXyFj2CoumG9Q9YVe+k2+Q3ADt5JZLK6R91FUMX88Pi9llKf5p5GQl10uKgMUjXDvqZVXRKHBUN8Swaa3h+PNJH1luytxhuW15U4d1NqURunMvCU2MXGql2PZB3spn+Z8tiJECuARUX5SVW48cc7CUb+hbVICLk1uHDo=
app: peaceful-reef-61917
  on:
    branch: main
  run: rails db:migrate
